/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e1e0ff',
        'on-tertiary-container': '#fffbff',
        'primary-fixed-dim': '#c0c1ff',
        'surface-container-highest': '#d8e3fb',
        'error': '#ba1a1a',
        'surface-bright': '#f9f9ff',
        'secondary': '#6b38d4',
        'error-container': '#ffdad6',
        'surface-container': '#e7eeff',
        'tertiary-fixed-dim': '#ffb783',
        'on-background': '#111c2d',
        'secondary-fixed-dim': '#d0bcff',
        'on-primary-container': '#fffbff',
        'inverse-surface': '#263143',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#703700',
        'on-primary-fixed': '#07006c',
        'inverse-primary': '#c0c1ff',
        'secondary-container': '#8455ef',
        'tertiary': '#904900',
        'surface-variant': '#d8e3fb',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e9ddff',
        'on-primary-fixed-variant': '#2f2ebe',
        'primary-container': '#6063ee',
        'outline-variant': '#c7c4d7',
        'tertiary-fixed': '#ffdcc5',
        'surface-container-high': '#dee8ff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b55d00',
        'on-secondary-fixed-variant': '#5516be',
        'surface-container-low': '#f0f3ff',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface': '#f9f9ff',
        'surface-tint': '#494bd6',
        'on-surface': '#111c2d',
        'primary': '#4648d4',
        'on-surface-variant': '#464554',
        'background': '#f9f9ff',
        'inverse-on-surface': '#ecf1ff',
        'outline': '#767586',
        'on-tertiary-fixed': '#301400',
        'surface-dim': '#cfdaf2',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '32px',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}